DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;


CREATE TABLE IF NOT EXISTS products (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
  name VARCHAR(45) not NULL,
  price INT not NULL,
  status VARCHAR(45) not NULL,
  created_at datetime default CURRENT_TIMESTAMP,
  CONSTRAINT PK_products PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS orders (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
  user_id INT,
  status VARCHAR(45) NOT NULL,
  created_at VARCHAR(45) NOT NULL,
  CONSTRAINT PK_orders PRIMARY KEY (id)
  );
    
CREATE TABLE IF NOT EXISTS order_items (
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT DEFAULT 0,
  CONSTRAINT PK_order_items PRIMARY KEY (order_id, product_id)
);

ALTER TABLE order_items 
ADD CONSTRAINT FK_products FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE order_items 
ADD CONSTRAINT FK_orders FOREIGN KEY (order_id) REFERENCES orders(id);

CREATE USER "dbUser" PASSWORD 'userPassword';

CREATE ROLE "dbUserRole";
GRANT "dbUserRole" TO "dbUser";

GRANT SELECT, UPDATE, INSERT ON TABLE order_items TO "dbUserRole";
GRANT SELECT, UPDATE, INSERT ON TABLE products TO "dbUserRole";
GRANT SELECT, UPDATE, INSERT ON TABLE orders TO "dbUserRole";
 
INSERT INTO products ( name, price, status) VALUES
('Spoon', '1', 'in_stock'),
('Fork', '3', 'in_stock'),
('Knife', '5', 'in_stock');

INSERT INTO orders (user_id, status, created_at) VALUES
('1', 'in_stock', '2021-02-16 18:50:51.66'),
('2', 'in_stock', '2021-02-16 18:50:51.66'),
('3', 'in_stock', '2021-02-16 18:50:51.66');

INSERT INTO order_items (order_id, product_id, quantity) VALUES
(1, 1, 10),
(3, 2, 10),
(3, 3, 10),
(2, 2, 30),
(2, 3, 20);

CREATE USER "dbDeleteUser" PASSWORD "dbDeletePassword"
CREATE ROLE "dbRoleDelete"
GRANT "dbRoleDelete" TO "dbDeleteUser"
GRANT SELECT, DELETE ON TABLE order_items TO "dbDeleteUser" 
GRANT SELECT, DELETE ON TABLE products TO "dbDeleteUser"
GRANT SELECT, DELETE ON TABLE orders TO "dbDeleteUser"
 